---
# tasks file for debian-nextcloud
- name: install commons
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - vim
    - git
    - wget
    - gnupg2
    - dirmngr
    - lsb-release
    - ssl-cert
    - ca-certificates
- name: test sources.list backup
  stat: path=/etc/apt/sources.list.bak
  register: sources_list_stat
- name: backup sources.list
  command: cp /etc/apt/sources.list /etc/apt/sources.list.bak
  when: not sources_list_stat.stat.exists
- name: add repo in sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
- name: add sury repo key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    keyring: /etc/apt/trusted.gpg.d/php.gpg
- name: add nginx repo key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    keyring: /etc/apt/trusted.gpg.d/nginx.gpg
- name: add mariadb repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F1656F24C74CD1D8
- name: install other commons
  apt: name={{ item }} state=latest
  with_items:
    - software-properties-common
    - zip
    - unzip
    - screen
    - curl
    - git
    - ffmpeg
    - libfile-fcntllock-perl
- name: nginx installation
  include: nginx-install.yml
- name: PHP installation & configuration
  include: php.yml
- name: MariaDB installation & configuration
  include: mariadb.yml
- name: redis installation
  include: redis.yml
- name: nginx configuration
  include: nginx-conf.yml
- name: nextcloud binaries download
  include: nc-download.yml
- name: installation certbot
  include: certbot.yml
- name: nextcloud installation & configuration
  include: nc-install.yml
...
