---
#- name: get nextcloud checksum
#  uri: url=https://download.nextcloud.com/server/releases/latest.tar.bz2.sha256 return_content=true
#  register: wp_checksum
- name: download nextcloud
  get_url:
    url: https://download.nextcloud.com/server/releases/latest.tar.bz2
    dest: /root
- name: fix permission /var/www
  file:
    path: /var/www
    owner: www-data
    group: www-data
    recurse: yes
- name: extract nextcloud archive
  unarchive:
    src: /root/latest.tar.bz2
    dest: /var/www
    remote_src: yes
  tags: extract_nextcloud
...
