- name: install php
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - ["php7.3-fpm","php7.3-gd","php7.3-mysql","php7.3-curl","php7.3-xml","php7.3-zip","php7.3-intl","php7.3-mbstring","php7.3-json","php7.3-bz2","php7.3-ldap","php-apcu","imagemagick","php-imagick"]
- name: Adjust time & date
  timezone:
    name: Europe/Paris
- name: configure PHP www.conf
  replace:
    path: /etc/php/7.3/fpm/pool.d/www.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
    backup: yes
  with_items:
    - { regexp: ';env\[HOSTNAME\]', replace: 'env[HOSTNAME]' }
    - { regexp: ';env\[TMP\]', replace: 'env[TMP]' }
    - { regexp: ';env\[TMPDIR\]', replace: 'env[TMPDIR]' }
    - { regexp: ';env\[TEMP\]', replace: 'env[TEMP]' }
    - { regexp: ';env\[PATH\]', replace: 'env[PATH]' }
    - { regexp: 'pm.max_children = .*', replace: 'pm.max_children = 240' }
    - { regexp: 'pm.start_servers = .*', replace: 'pm.start_servers = 20' }
    - { regexp: 'pm.min_spare_servers = .*', replace: 'pm.min_spare_servers = 10' }
    - { regexp: 'pm.max_spare_servers = .*', replace: 'pm.max_spare_servers = 20' }
    - { regexp: ';pm.max_requests = 500', replace: 'pm.max_requests = 500' }
- name: configure PHP cli
  replace:
    path: /etc/php/7.3/cli/php.ini
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
    backup: yes
  with_items:
    - { regexp: 'output_buffering =.*', replace: 'output_buffering = "Off"' }
    - { regexp: 'max_execution_time =.*', replace: 'max_execution_time = 1800' }
    - { regexp: 'max_input_time =.*', replace: 'max_input_time = 3600' }
    - { regexp: 'post_max_size =.*', replace: 'post_max_size = 10240M' }
    - { regexp: 'upload_max_filesize =.*', replace: 'upload_max_filesize = 10240M' }
    - { regexp: 'max_file_uploads =.*', replace: 'max_file_uploads = 100' }
    - { regexp: ';date.timezone.*', replace: 'date.timezone = Europe\/\Paris/' }
    - { regexp: ';session.cookie_secure.*', replace: 'session.cookie_secure = True' }
    - { regexp: ';session.save_path =.*', replace: 'session.save_path = \"N;700;\/usr\/local\/tmp\/sessions\"' }
- name: enable apc in php cli
  lineinfile:
    path: /etc/php/7.3/cli/php.ini
    insertafter: '; End:'
    line: 'apc.enable_cli = 1'
    state: present
- name: configure PHP fpm
  replace:
    path: /etc/php/7.3/fpm/php.ini
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
    backup: yes
  with_items:
    - { regexp: 'memory_limit = 128M', replace: 'memory_limit = 512M' }
    - { regexp: 'output_buffering =.*', replace: 'output_buffering = Off' }
    - { regexp: 'max_execution_time =.*', replace: 'max_execution_time =.*' }
    - { regexp: 'max_input_time =.*', replace: 'max_input_time =.*' }
    - { regexp: 'post_max_size =.*', replace: 'post_max_size = 10240M' }
    - { regexp: 'upload_max_filesize =.*', replace: 'upload_max_filesize = 10240M' }
    - { regexp: 'max_file_uploads =.*', replace: 'max_file_uploads = 100' }
    - { regexp: ';date.timezone.*', replace: 'date.timezone = Europe\/\Paris/' }
    - { regexp: ';session.cookie_secure.*', replace: 'session.cookie_secure = True' }
    - { regexp: ';opcache.enable=.*', replace: 'opcache.enable=1' }
    - { regexp: ';opcache.enable_cli=.*', replace: 'opcache.enable_cli=1' }
    - { regexp: ';opcache.memory_consumption=.*', replace: 'opcache.memory_consumption=128' }
    - { regexp: ';opcache.interned_strings_buffer=.*', replace: 'opcache.interned_strings_buffer=8' }
    - { regexp: ';opcache.max_accelerated_files=.*', replace: 'opcache.max_accelerated_files=10000' }
    - { regexp: ';opcache.revalidate_freq=.*', replace: 'opcache.revalidate_freq=1' }
    - { regexp: ';opcache.save_comments=.*', replace: 'opcache.save_comments=1' }
    - { regexp: ';session.save_path =.*', replace: 'session.save_path = \"N;700;\/usr\/local\/tmp\/sessions\"' }
- name: configure php-fpm.conf
  replace:
    path: /etc/php/7.3/fpm/php-fpm.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
    backup: yes
  with_items:
    - { regexp: ';emergency_restart_threshold =.*', replace: 'emergency_restart_threshold = 10' }
    - { regexp: ';emergency_restart_interval =.*', replace: 'emergency_restart_interval = 1m' }
    - { regexp: ';process_control_timeout =.*', replace: 'process_control_timeout = 10s' }
- name: enable apc in php fpm
  blockinfile:
    path: /etc/php/7.3/fpm/php.ini
    insertafter: '; End:'
    block: |
      'apc.enable_cli = 1'
      'apc.file_update_protection=2'
      'apc.optimization=0'
      'apc.shm_size=256M'
      'apc.include_once_override=0'
      'apc.shm_segments=1'
      'apc.ttl=7200'
      'apc.user_ttl=7200'
      'apc.gc_ttl=3600'
      'apc.num_files_hint=1024'
      'apc.max_file_size=5M'
      'apc.cache_by_default=1'
      'apc.use_request_time=1'
      'apc.slam_defense=0'
      'apc.mmap_file_mask=/usr/local/tmp/apc/apc.XXXXXX'
      'apc.stat_ctime=0'
      'apc.canonicalize=1'
      'apc.write_lock=1'
      'apc.report_autofilter=0'
      'apc.rfc1867=0'
      'apc.rfc1867_prefix =upload_'
      'apc.rfc1867_name=APC_UPLOAD_PROGRESS'
      'apc.rfc1867_freq=0'
      'apc.rfc1867_ttl=3600'
      'apc.lazy_classes=0'
      'apc.lazy_functions=0'
- name: modify fstab apc
  mount:
    path: /usr/local/tmp/apc
    src: tmpfs
    fstype: tmpfs
    opts: defaults,uid=33,size=300M,noatime,nosuid,nodev,noexec,mode=1777
    state: present
- name: modify fstab sessions
  mount:
    path: /usr/local/tmp/sessions
    src: tmpfs
    fstype: tmpfs
    opts: defaults,uid=33,size=300M,noatime,nosuid,nodev,noexec,mode=1777
    state: present
#- name: create cron "session clean"
#  cron:
#    name: "session clean"
#    minute: "09"
#    hour: "39"
#    job: "/usr/lib/php/sessionclean 2>&1"
- name: comment php cron
  replace:
    path: /etc/cron.d/php
    regexp: '^09,39.*'
    replace: '# 09,39 *     * * *     root   [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi'
    backup: yes
